## Softmax 

In [37]:
import numpy as np
def convert_one_hot(y, k):
    one_hot = np.zeros((len(y), k))
    print(one_hot)
    print(np.arange(len(y)))
    one_hot[np.arange(len(y)), y] = 1
    print(one_hot)


In [38]:
convert_one_hot([0,1,2,1,2,0], 3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3 4 5]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [39]:
label = ['a','b','c','b','c','a']
one = set(label)

In [47]:
label_embed = []
for i in label:
    for j, value in enumerate(one):
        if i == value:
            label_embed.append(j)
            continue
label_embed 

[1, 0, 2, 0, 2, 1]

In [48]:
def conver_one_hot(label_embed, k):
    one_hot = np.zeros((len(label_embed), k))
    one_hot[np.arange(len(label_embed)), label_embed] = 1
    return one_hot
conver_one_hot(label_embed, len(one))

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [92]:
import numpy as np

In [93]:
x = np.array([[1,0.5]])
y = np.array([1])

In [97]:
def one_hot(y,c):
    one_hot_z = np.zeros((len(y), c))
    one_hot_z[np.arange(len(y)), y] = 1
    return one_hot_z


In [98]:
c = 4
one_hot(y, c)

array([[0., 1., 0., 0.]])

In [99]:
arr = [1,2,3,4]
print(np.arange(len(arr)))

[0 1 2 3]
