In [2]:
import torch

In [3]:
data = [1,2,3]
data = torch.tensor(data)
print(data)

tensor([1, 2, 3])


In [4]:
import numpy as np

In [5]:
data= np.array([1,2,3])
data = torch.from_numpy(data)
print(data)

tensor([1, 2, 3])


In [6]:
data = torch.randn(3,3)
print(data)

tensor([[-0.4659,  0.0267,  0.8273],
        [ 0.3933,  0.3874,  0.4475],
        [ 1.0839,  1.3580, -0.4888]])


In [9]:
data = torch.arange(start=0, end=5, step=1)
data

tensor([0, 1, 2, 3, 4])

In [12]:
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([1])
tensor3 = tensor1 + tensor2
tensor3

tensor([[2, 3],
        [4, 5]])

In [13]:
x = torch.tensor([[1,2],[3,4]])
square = x**2   
square

tensor([[ 1,  4],
        [ 9, 16]])

In [16]:
x = torch.tensor([1.0,2.0,3.0,4.0])
y  = torch.tensor([5.0,6.0,7.0,8.0])
loss_fn = torch.nn.MSELoss()
loss = loss_fn(x,y)
loss

tensor(16.)